"""Item icons (16x16 pixel art), armour layers and pack icons."""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from PIL import Image, ImageDraw  # noqa: E402

from mcmodel import Cube, Model  # noqa: E402
from mctexture import Painter  # noqa: E402
import palettes  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RP = os.path.join(ROOT, "packs", "kaiju8_RP")
ITEM_DIR = os.path.join(RP, "textures", "items")
ARMOR_DIR = os.path.join(RP, "textures", "models", "armor")

C = {
    ".": None,
    "k": (24, 22, 28), "d": (56, 58, 68), "g": (120, 126, 138),
    "s": (178, 186, 198), "w": (232, 236, 242), "W": (252, 253, 255),
    "b": (74, 158, 236), "B": (150, 214, 255), "n": (30, 34, 48),
    "r": (198, 42, 54), "R": (255, 96, 80), "c": (120, 26, 34),
    "o": (232, 126, 42), "O": (255, 182, 72), "y": (255, 222, 110),
    "p": (110, 72, 140), "P": (255, 62, 148),
    "m": (120, 96, 66), "M": (168, 142, 104),
    "e": (98, 112, 88), "E": (146, 166, 124),
    "f": (166, 120, 116), "h": (226, 220, 204), "H": (246, 242, 232),
    "x": (92, 98, 110), "t": (58, 40, 30),
}

ICONS = {}

ICONS["kaiju_core"] = """
................
......kkkk......
....kkcccckk....
...kccoooocckk..
..kcoo0OOoocck..
..kco0OyyOo0ck..
.kccoOyWWyOocck.
.kcoOyWWWWyOock.
.kcoOyWWWWyOock.
.kccoOyWWyOocck.
..kco0OyyOo0ck..
..kcoo0OOoocck..
...kccoooocckk..
....kkcccckk....
......kkkk......
................
""".replace("0", "o")

ICONS["kaiju_shell"] = """
................
....kkkkkk......
..kkeeeeEEkk....
.keeEEeeeeEEk...
.keEEeeeeeeEEk..
.keeeeEEeeeeek..
.kEEeeeeEEeeEk..
.keeeeeeeeeeEk..
.keEEeeeeEEeek..
.keeeeEEeeeeEk..
.kEEeeeeeeeeek..
..keeEEeeeeek...
..kkeeeeEEkk....
....kkkkkkk.....
................
................
"""

ICONS["kaiju_alloy"] = """
................
................
................
................
....kkkkkkkk....
...kwwwwwwwwk...
..kwsssssssswk..
.kwsbbBBbbbbswk.
.kwsbBBWWBBbswk.
.kwsbbBBbbbbswk.
..kwsssssssswk..
...kxxxxxxxxk...
....kkkkkkkk....
................
................
................
"""

ICONS["no8_power"] = """
................
.......kk.......
.....kknnkk.....
...kknnnnnnkk...
..knnnBnnBnnnk..
..knnBWnnWBnnk..
.knnnnBnnBnnnnk.
.knnBWnnnnWBnnk.
.knnnBnnnnBnnnk.
.knnnnBnnBnnnnk.
..knnBWnnWBnnk..
..knnnBnnBnnnk..
...kknnnnnnkk...
.....kknnkk.....
.......kk.......
................
"""

ICONS["kaiju_remains"] = """
................
................
.....kkk.kk.....
...kkeEekeEkk...
..kefffekeffek..
.keffcfffcffek..
.kefcfffffcfek..
.keffffcffffek..
..kefffffffek...
...kkeffffekk...
.....kkeeekk....
.......kkk......
................
................
................
................
"""

ICONS["combat_knife"] = """
................
................
................
...........WW...
..........Wss...
.........Wsss...
........Wsss....
.......Wsss.....
......Wssg......
.....kkkg.......
....kdddk.......
...kdddk........
...kddk.........
...kkk..........
................
................
"""

ICONS["df_rifle"] = """
................
................
.............ggg
..........kkkksg
.........kdddddk
....kkkkkddddddk
...kddddddddddk.
...kdbbbdddkk...
...kdddddkk.....
....kkdddk......
......kddk......
.......kddk.....
........kddk....
.........kdk....
..........kk....
................
"""

ICONS["cannon_t25"] = """
...........kkkkk
.........kkssssk
.......kkssssssk
....kkkksbBbsskk
..kkddddddbBdk..
.kdddbBBBbdddk..
.kddddddddddk...
.kdbbbdddkkk....
.kdddddkk.......
..kkdddk........
....kddk........
.....kddk.......
......kddk......
.......kddk.....
........kdk.....
.........kk.....
"""

ICONS["twin_sw2033"] = """
............W.W.
...........WsWs.
..........WssWs.
.........Wss.Ws.
........Wss.Wss.
.......Wss.Wss..
......Wss.Wss...
.....Wsg.Wsg....
....kkg.kkg.....
...kdkkkdk......
..kdkkkdk.......
..kk.kkk........
.....k..........
................
................
................
"""

ICONS["axe_03ax"] = """
................
.......kkkkk....
.....kkksssskk..
...kkWWWWWWWsdk.
..kWWWWWWWWWsdk.
.kWWWWWWWWWWsdk.
.kWWWWWWWWWWsdk.
..kWWWWWWWWWsdk.
...kkWWWWWWsddk.
.....kkkkkksddk.
..........kddk..
.........kddk...
........kddk....
.......kddk.....
......kddk......
......kk........
"""

ICONS["gunblade_gs3305"] = """
................
..........kkkk..
.........kssssk.
........kssWWsk.
.......kssWWsk..
......kssWWsk...
.....kssWWsk....
....kssWWsk.....
...kddWWsk......
..kdddWsk.......
..kdgdkk........
..kddk..........
..kdk...........
..kk............
................
................
"""

ICONS["df_pistol"] = """
................
................
................
.....kkkkkkk....
....kdddddddk...
...kdsssssddk...
...kddddddddk...
...kdgdkkkkk....
...kdgdk........
...kdgdk........
...kegek........
...kdddk........
....kkk.........
................
................
................
"""

ICONS["df_bazooka"] = """
................
................
..kkkkkkkkkkkk..
.ksddddddddddsk.
.kdddddddddddsk.
.ksddddddddddsk.
..kkkkkkkkkkkk..
.....kdgdk......
.....kdgdk......
......kkk.......
................
................
................
................
................
................
"""

ICONS["blade_sw1023"] = """
..............WW
.............Wsk
............Wsk.
...........Wsk..
..........Wsk...
.........Wsk....
........Wsk.....
.......Wsk......
......Wsk.......
.....Wsk........
....kkk.........
...kdkk.........
..kdk...........
..kdk...........
..kk............
................
"""

ICONS["identified_core"] = """
................
......kkkk......
....kkBBBBkk....
...kBBWWWWBBk...
..kBBWWccWWBBk..
..kBWWccccWWBk..
.kBBWcccccc WBk.
.kBWcccWWcccWBk.
.kBWcccWWcccWBk.
.kBBWcccccccWBk.
..kBWWccccWWBk..
..kBBWWccWWBBk..
...kBBWWWWBBk...
....kkBBBBkk....
......kkkk......
................
""".replace(" ", "c")

def _numbers_icon(body, trim, glow, mark):
    return f"""
................
....{trim}{trim}{trim}{trim}{trim}{trim}{trim}{trim}....
...{trim}{body}{body}{body}{body}{body}{body}{body}{body}{trim}...
..{trim}{body}{glow}{body}{body}{body}{body}{glow}{body}{trim}..
..{trim}{body}{body}{body}{mark}{mark}{body}{body}{body}{trim}..
..{trim}{body}{body}{mark}{mark}{mark}{mark}{body}{body}{trim}..
..{trim}{body}{body}{body}{mark}{mark}{body}{body}{body}{trim}..
..{trim}{body}{glow}{body}{body}{body}{body}{glow}{body}{trim}..
..{trim}{body}{body}{body}{body}{body}{body}{body}{body}{trim}..
...{trim}{body}{body}{body}{body}{body}{body}{body}{body}{trim}...
....{trim}{trim}{body}{body}{body}{body}{trim}{trim}....
......{trim}{body}{body}{body}{body}{trim}......
......{trim}{trim}{trim}{trim}{trim}{trim}......
................
................
................
"""

ICONS["numbers_1"] = _numbers_icon("k", "d", "R", "w")
ICONS["numbers_2"] = _numbers_icon("g", "w", "y", "s")
ICONS["numbers_4"] = _numbers_icon("w", "y", "O", "s")
ICONS["numbers_6"] = _numbers_icon("n", "d", "B", "w")
ICONS["numbers_10"] = _numbers_icon("p", "E", "E", "R")

ICONS["combat_suit_helmet"] = """
................
....kkkkkkkk....
..kkwwwwwwwwkk..
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
.kwkkkkkkkkkkwk.
.kwkbBBbbBBbkwk.
.kwkkkkkkkkkkwk.
.kwwddddddddwwk.
..kwddddddddwk..
..kwwddddddwwk..
...kkwwwwwwkk...
.....kkkkkk.....
................
................
"""

ICONS["combat_suit_chestplate"] = """
................
.kkkk......kkkk.
.kwwwk....kwwwk.
.kwwwkkkkkkwwwk.
.kwwwwwwwwwwwwk.
.kwwwwwbBwwwwwk.
.kwwddwbBwddwwk.
.kwwddwwwwwddwk.
.kwwwwwwwwwwwwk.
.kwwwdddddddwwk.
.kwwwdddddddwwk.
.kwwwwddddwwwwk.
.kkwwwwwwwwwwkk.
..kkkkkkkkkkkk..
................
................
"""

ICONS["combat_suit_leggings"] = """
................
................
..kkkkkkkkkkkk..
.kwwwwwwwwwwwwk.
.kwwddddddddwwk.
.kwwddbBbbddwwk.
.kwwddddddddwwk.
.kwwwwddddwwwwk.
.kwwwwk..kwwwwk.
.kwwddk..kddwwk.
.kwwddk..kddwwk.
.kwwddk..kddwwk.
.kwwwwk..kwwwwk.
.kkkkkk..kkkkkk.
................
................
"""

ICONS["combat_suit_boots"] = """
................
................
................
................
................
.kkkkkk..kkkkkk.
.kwwwwk..kwwwwk.
.kwddwk..kwddwk.
.kwddwk..kwddwk.
.kwwwwk..kwwwwk.
.kwbBwk..kwbBwk.
kkwwwwkkkkwwwwkk
kwwwwwwkkwwwwwwk
kwddddwkkwddddwk
kkkkkkkkkkkkkkkk
................
"""

ICONS["kaiju_detector"] = """
................
................
....kkkkkkkk....
...kddddddddk...
..kdwwwwwwwwdk..
..kdwnnnnnnwdk..
..kdwnRnnRnwdk..
..kdwnnRRnnwdk..
..kdwnRnnRnwdk..
..kdwnnnnnnwdk..
..kdwwwwwwwwdk..
...kdbBbbBbdk...
...kddddddddk...
....kkkkkkkk....
................
................
"""

ICONS["parasite_kaiju"] = """
................
................
........kkkk....
......kkffffk...
.....kfRffffk...
....kffffffk....
...kfffffkk.....
..kcffffk.......
..kcfffk........
...kcffk........
....kcfk........
.....kck........
......kk........
................
................
................
"""


def draw_icon(name: str, art: str) -> None:
    rows = [r for r in art.strip("\n").split("\n") if r]
    img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows[:16]):
        for x, ch in enumerate(row[:16]):
            col = C.get(ch)
            if col:
                px[x, y] = (col[0], col[1], col[2], 255)
    os.makedirs(ITEM_DIR, exist_ok=True)
    img.save(os.path.join(ITEM_DIR, name + ".png"))


def armour_layers() -> None:
    os.makedirs(ARMOR_DIR, exist_ok=True)
    pal = {
        "armor": palettes.OFFICER["armor"],
        "suit": palettes.OFFICER["suit"],
        "accent": palettes.OFFICER["accent"],
    }
    for layer in (1, 2):
        m = Model(f"armor_{layer}", 64, 32)
        b = m.bone("armor")
        if layer == 1:
            b.add(Cube((-4, 24, -4), (8, 8, 8), "armor", fixed_uv=[0, 0],
                       decals={"north": "visor"}))
            b.add(Cube((-4, 12, -2), (8, 12, 4), "armor", fixed_uv=[16, 16],
                       decals={"north": "core"}))
            b.add(Cube((-8, 12, -2), (4, 12, 4), "suit", fixed_uv=[40, 16]))
            b.add(Cube((-4, 0, -2), (4, 12, 4), "suit", fixed_uv=[0, 16]))
        else:
            b.add(Cube((-4, 12, -2), (8, 12, 4), "suit", fixed_uv=[16, 16]))
            b.add(Cube((-4, 0, -2), (4, 12, 4), "armor", fixed_uv=[0, 16]))
        p = Painter(64, 32, 5 + layer)
        p.paint_model(m, pal)
        p.save(os.path.join(ARMOR_DIR, f"kaiju8_suit_layer_{layer}.png"))
        print(f"  armor layer {layer}")


def pack_icon(path: str, accent=(126, 216, 255)) -> None:
    size = 128
    img = Image.new("RGBA", (size, size), (14, 16, 24, 255))
    d = ImageDraw.Draw(img)
    for i in range(size):
        t = i / size
        d.line([(0, i), (size, i)], fill=(int(14 + 26 * t), int(16 + 26 * t), int(24 + 44 * t), 255))
    # claw slashes
    for k, off in enumerate((-26, 0, 26)):
        d.line([(18 + off, 8), (66 + off, 120)], fill=(80, 20, 26, 255), width=9)
        d.line([(18 + off, 8), (66 + off, 120)], fill=(168, 34, 44, 255), width=4)
    # the "8"
    for cy, rr in ((46, 22), (86, 26)):
        d.ellipse([64 - rr, cy - rr, 64 + rr, cy + rr], outline=accent, width=7)
        d.ellipse([64 - rr, cy - rr, 64 + rr, cy + rr], outline=(255, 255, 255, 190), width=2)
    d.rectangle([0, 0, size - 1, size - 1], outline=(226, 224, 214, 255), width=3)
    img.save(path)


def main() -> None:
    print("item icons:")
    for name, art in ICONS.items():
        draw_icon(name, art)
        print("  " + name)
    armour_layers()
    pack_icon(os.path.join(RP, "pack_icon.png"))
    pack_icon(os.path.join(ROOT, "packs", "kaiju8_BP", "pack_icon.png"), (255, 150, 80))
    print("  pack icons")


if __name__ == "__main__":
    main()
